<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- site css -->
    <link rel="stylesheet" href="/css/a.min.css">
    <link href="/css/font-face.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/js/site.min.js"></script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/js/bdue/lang/zh-cn/zh-cn.js"></script>
</head>
<body>
<?php include APPLICATION_PATH."/application/modules/Admin/views/site/nav.phtml" ?>
<div class="container-fluid">
    <!--documents-->
    <div class="row row-offcanvas row-offcanvas-left">
        <?php include APPLICATION_PATH."/application/modules/Admin/views/site/header.phtml" ?>
        <div class="col-xs-12 col-sm-9 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $title;?></h3>
                </div>
                <div class="panel-body">
                    <div class="content-row">
                        <h2 class="content-row-title"><?php echo $title;?></h2>
                        <div class="row">
                            <form class="form-horizontal" method="post"  action="/admin/article/add">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">标题</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="标题" id="title" class="form-control" name="title" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">分类</label>
                                    <div class="col-md-10">
                                        <select class="form-control input-sm" name="catid">
                                            <?php foreach($category_list as $l){?>
                                                <option value="<?php echo $l['id']?>"><?php echo $l["category"];?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">关键字</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="关键字" id="keyword" class="form-control" name="keyword" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="description">描述</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="描述" id="description" class="form-control" name="description" value="">
                                    </div>
                                </div>
                                <div class="from-group">
                                    <label class="col-md-2 control-label">内容介绍</label>
                                    <div class="col-md-10">
                                        <!-- 加载编辑器的容器 -->
                                        <textarea id="container" name="content" style="height:400px;"></textarea>
                                        <!-- 配置文件 -->
                                        <script type="text/javascript" src="/js/bdue/ueditor.config.js"></script>
                                        <!-- 编辑器源码文件 -->
                                        <script type="text/javascript" src="/js/bdue/ueditor.all.js"></script>
                                        <!-- 实例化编辑器 -->
                                        <script type="text/javascript">
                                            var ue = UE.getEditor('container');
                                        </script>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">推荐值</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="推荐值" id="recommend" class="form-control" name="recommend" value="0">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button class="btn btn-info" type="submit">添加</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div><!-- panel body -->
            </div>
        </div><!-- content -->
    </div>
</div>
</body>
</html>