<div class="site-footer">
    <div class="container-fluid">
        <div class="copyright clearfix">
            <p>
                <a href="/">aaa</a>&nbsp;&bull;&nbsp;
                <a href="/app/">bbb</a>&nbsp;&bull;&nbsp;
                <a href="/article/">ccc</a>&nbsp;&bull;&nbsp;
                <a href="/page/top.html">ddd</a>
            </p>
            <p>&copy; www.aabbcc.com 2018</p>
        </div>
    </div>
</div>
</body>
</html>