<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><?php echo $title;?></title>
  <?php if(isset($keyword)){?>
  <meta name="keywords" content="<?php echo $keyword;?>" />
  <?php } if(isset($description)){?>
  <meta name="description" content="<?php echo $description;?>" />
  <?php }?>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
  <link rel="shortcut icon" href="favicon_16.ico"/>
  <link rel="bookmark" href="favicon_16.ico"/>
  <link rel="stylesheet" href="/css/site.min.css">
  <link href="/css/font-face.css" rel="stylesheet" type="text/css">
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <script type="text/javascript" src="/js/site.min.js"></script>
</head>
<body>
<nav role="navigation" class="navbar navbar-custom">
    <div class="container-fluid">
        <div class="navbar-header">
            <button data-target="#bs-content-row-navbar-collapse-5" data-toggle="collapse" class="navbar-toggle" type="button">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><img src="/img/logo.jpg" width="90" height="45" alt="" /> </a>
        </div>
        <div id="bs-content-row-navbar-collapse-5" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php foreach($menu as $m){?>
                    <li><a href="<?php echo $m['link'];?>"><?php echo $m['text'];?></a></li>
                <?php } ?>
            </ul>

        </div>
    </div>
</nav>