<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- site css -->
    <link rel="stylesheet" href="/css/a.min.css">
    <link href="/css/font-face.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/js/site.min.js"></script>
</head>
<body>
<?php include APPLICATION_PATH."/application/modules/Admin/views/site/nav.phtml" ?>
<div class="container-fluid">
    <!--documents-->
    <div class="row row-offcanvas row-offcanvas-left">
        <?php include APPLICATION_PATH."/application/modules/Admin/views/site/header.phtml" ?>
        <div class="col-xs-12 col-sm-9 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $title;?></h3>
                </div>
                <div class="panel-body">

                    <?php if($msg!=""){?>
                    <div class="content-row">
                        <div class="alert alert-info alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <?php echo $msg;?>
                        </div>
                    </div>
                    <?php }?>

                    <div class="content-row">
                        <h2 class="content-row-title"><?php echo $title;?></h2>
                        <div class="row">
                            <form class="form-horizontal" method="post"  action="/admin/page/edit">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">名称</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="英文名称" id="name" class="form-control" name="name" value="<?php echo $page["name"];?>">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">标题</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="标题" id="title" class="form-control" name="title" value="<?php echo $page["title"];?>">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">关键字</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="关键字" id="keyword" class="form-control" name="keyword" value="<?php echo $page["keyword"];?>">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="description">描述</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="描述" id="description" class="form-control" name="description" value="<?php echo $page["description"];?>">
                                    </div>
                                </div>
                                <div class="from-group">
                                    <label class="col-md-2 control-label">内容介绍</label>
                                    <div class="col-md-10">
                                        <!-- 加载编辑器的容器 -->
                                        <textarea id="container" name="content" style="height:400px;"><?php echo $page["content"];?></textarea>
                                        <!-- 配置文件 -->
                                        <script type="text/javascript" src="/js/bdue/ueditor.config.js"></script>
                                        <!-- 编辑器源码文件 -->
                                        <script type="text/javascript" src="/js/bdue/ueditor.all.js"></script>
                                        <!-- 实例化编辑器 -->
                                        <script type="text/javascript">
                                            var ue = UE.getEditor('container');
                                        </script>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="hidden" name="id" value="<?php echo $page['id'];?>">
                                        <button class="btn btn-info" type="submit">修改</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div><!-- panel body -->
            </div>
        </div><!-- content -->

    </div>
</div>
</body>
</html>