<?php include APPLICATION_PATH."/application/views/site/header.phtml" ?>
<div class="container-fluid">
    <div class="col-xs-12 col-md-9 col-lg-9 col-sm-8 content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">热门推荐</h3>
            </div>
            <div class="panel-body">
                    <ul class="list-group">
                        <?php foreach ($top_list as $l){?>
                            <li class="list-group-item">
                                <span class="badge badge-default"><span class="fa  fa-heart"><span class="label"><?php echo $l["views"];?></span></span></span>
                                <a class="weight" href="<?php echo $l["link"]?>"><?php  echo $l["title"];?></a>
                                <span class="date">更新时间：<?php echo date('Y-m-s',$l["updated"]);?></span>
                            </li>
                        <?php } ?>
                        <?php foreach ($article_top_list as $l){?>
                            <li class="list-group-item">
                                <span class="badge badge-default"><span class="fa  fa-heart"><span class="label"><?php echo $l["views"];?></span></span></span>
                                <a class="red" href="<?php echo $l["link"]?>"><?php  echo $l["title"];?></a>
                                <span class="date">更新时间：<?php echo date('Y-m-s',$l["updated"]);?></span>
                            </li>
                        <?php } ?>
                    </ul>
            </div>
        </div>

        <div class="panel panel-default">
             <div class="panel-heading">
                 <h3 class="panel-title"><?php echo $category["category"];?></h3>
             </div>
             <div class="panel-body">
                 <ul class="list-group">
                      <?php foreach ($article_list as $l){?>
                          <li class="list-group-item">
                              <span class="badge badge-default"><span class="fa  fa-heart-o"><span class="label"><?php echo $l["views"];?></span></span></span>
                              <a class="red" href="<?php echo  \Until\Url::createurl("article","content",["id"=>$l["id"]]);?>"><?php  echo $l["title"];?></a>
                              <span class="date">更新时间：<?php echo date('Y-m-s',$l["updated"]);?></span>
                          </li>
                       <?php } ?>
                  </ul>
             </div>
        </div>
    </div>
    <div class="col-xs-12 col-md-3 col-lg-3 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">aabbcc分类</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <?php foreach($category_list as $l){?>
                    <li class="list-group-item"><span class="fa fa-archive"></span><a href="<?php echo \Until\Url::createurl("article","list",["categoryid"=>$l["id"],"page"=>"1"])?>"><?php echo $l["category"];?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">相关阅读</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <?php foreach($article_new_list as $l){?>
                    <li class="list-group-item"><a href="<?php echo \Until\Url::createurl("article","content",["id"=>$l["id"]]);?>"><?php echo $l['title'];?></a></li>
                    <?php }?>
                </ul>
            </div>
        </div>
    </div>

    <div class="row content-row-pagination">
        <div class="col-md-12">
            <ul class="pagination">
                <?php if(($page -1) > 0) {?>
                    <li class="active"><a href="<?php echo \Until\Url::createurl("article","list",["page"=>$page -1,"categoryid"=>$category["id"]])?>" class="fa fa-chevron-left" title="上一页"></a></li>
                <?php }else{?>
                    <li class="disabled"><a href="<?php echo \Until\Url::createurl("article","list",["page"=>1,"categoryid"=>$category["id"]])?>" class="fa fa-chevron-left" title="上一页"></a></li>
                <?php } ?>

                <?php foreach($pageplay as $p){?>
                    <li<?php if($p["page"]==$page) echo ' class="active"';?>><a href="<?php echo $p["link"]?>"><?php echo $p["page"];?></a></li>
                <?php } ?>

                <?php if(($page + 1) > count($pageplay)) {?>
                    <li class="disabled"><a href="<?php echo \Until\Url::createurl("article","list",["page"=>count($pageplay),"categoryid"=>$category["id"]])?>" class="fa fa-chevron-left" title="下一页"></a></li>
                <?php }else{?>
                    <li class="active"><a href="<?php echo \Until\Url::createurl("article","list",["page"=>$page + 1,"categoryid"=>$category["id"]])?>" class="fa fa-chevron-left" title="下一页"></a></li>
                <?php } ?>
            </ul>
        </div>
    </div>

</div>
<?php include APPLICATION_PATH."/application/views/site/footer.phtml" ?>