<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- site css -->
    <link rel="stylesheet" href="/css/a.min.css">
    <link href="/css/font-face.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/js/site.min.js"></script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/js/bdue/lang/zh-cn/zh-cn.js"></script>
</head>
<body>
<?php include APPLICATION_PATH."/application/modules/Admin/views/site/nav.phtml" ?>
<div class="container-fluid">
    <!--documents-->
    <div class="row row-offcanvas row-offcanvas-left">
        <?php include APPLICATION_PATH."/application/modules/Admin/views/site/header.phtml" ?>
        <div class="col-xs-12 col-sm-9 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">管理首页</h3>
                </div>
                <div class="panel-body">
                    <div class="content-row">
                        <h2 class="content-row-title">各类信息页面统计</h2>
                        <div class="row">
                            <table class="table">
                                <tr>
                                    <th>#</th>
                                    <th>页面类型</th>
                                    <th>数量</th>
                                </tr>
                                <tr>
                                    <td>1</td>
                                    <td>APP总数</td>
                                    <td><?php echo $appcount;?></td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>已发布APP</td>
                                    <td><?php echo $appusecount;?></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>未发布APP</td>
                                    <td><?php echo $appnousecount;?></td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>文章总数</td>
                                    <td><?php echo $articlecount;?></td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>Page总数</td>
                                    <td><?php echo $pagecount;?></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div><!-- panel body -->
            </div>
        </div><!-- content -->
    </div>
</div>
</body>
</html>