<?php include APPLICATION_PATH."/application/views/site/header.phtml" ?>
<div class="container-fluid">
    <div class="col-md-12">
        <ol class="breadcrumb breadcrumb-arrow">
            <li><a href="<?php echo $mbnav[0]["link"]?>"><?php echo $mbnav[0]["txt"]?></a></li>
            <li class="active"><span><?php echo $mbnav[1]["txt"]?></span></li>
        </ol>
    </div>
    <div class="col-xs-12 col-md-9 col-lg-9 col-sm-8 content">

        <div class="panel panel-default">
            <div class="panel-body">
                <h1 class="text-center clearfix"><?php echo $page["title"];?></h1>
                <div class="box-info  clearfix">
                    <div class="col-xs-6 col-md-6 text-left">更新时间:<?php echo date("Y-m-d",$page["updated"])?></div>
                    <div class="col-xs-6 col-md-6 text-right">发布时间:<?php echo date("Y-m-d",$page["pubdate"]);?></div>
                </div>
                <div class="article clearfix">
                    <?php echo $page["content"]?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-md-3 col-lg-3 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">aabbcc大全</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <?php foreach($page_list as $l){?>
                        <li class="list-group-item"><span class="fa fa-archive"></span><a href="<?php echo \Until\Url::createurl("page","show",["name"=>$l["name"]])?>"><?php echo $l["title"];?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php include APPLICATION_PATH."/application/views/site/footer.phtml" ?>