<div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="navigation">
    <ul class="list-group panel">
        <li class="list-group-item"><i class="glyphicon glyphicon-align-justify"></i> <b>SIDE PANEL</b></li>
        <li class="list-group-item"><a href="/admin/index/index"><i class="glyphicon glyphicon-home"></i>首页</a></li>
        <li class="list-group-item"><a href="/admin/menu/list" ><i class="glyphicon glyphicon-th"></i>菜单管理</a></li>
        <li class="list-group-item"><a href="/admin/appcategory/list"><i class="glyphicon glyphicon-list-alt"></i>APP分类</a></li>
        <li class="list-group-item"><a href="/admin/category/list"><i class="glyphicon glyphicon-th-list"></i>文章分类</a></li>
        <li class="list-group-item"><a href="/admin/app/list"><i class="glyphicon glyphicon-phone"></i>APP管理</a></li>
        <li class="list-group-item"><a href="/admin/article/list"><i class="glyphicon glyphicon-unchecked"></i>文章管理</li>
        <li class="list-group-item"><a href="/admin/page/list" ><i class="glyphicon glyphicon-indent-left"></i>页面管理</a></li>
        <li class="list-group-item"><a href="/admin/conversion/list" ><i class="glyphicon glyphicon-calendar"></i>转化页管理</a></li>
        <li class="list-group-item"><a href="/admin/flink/list" ><i class="glyphicon glyphicon-transfer"></i>友情链接</a></li>
    </ul>
</div>