<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- site css -->
    <link rel="stylesheet" href="/css/a.min.css">
    <link href="/css/font-face.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/js/site.min.js"></script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/js/bdue/lang/zh-cn/zh-cn.js"></script>
</head>
<body>
<?php include APPLICATION_PATH."/application/modules/Admin/views/site/nav.phtml" ?>
<div class="container-fluid">
    <!--documents-->
    <div class="row row-offcanvas row-offcanvas-left">
        <?php include APPLICATION_PATH."/application/modules/Admin/views/site/header.phtml" ?>
        <div class="col-xs-12 col-sm-9 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $title;?></h3>
                </div>
                <div class="panel-body">
                    <div class="content-row">
                        <h2 class="content-row-title"><?php echo $title;?></h2>
                        <div class="row">
                            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="/admin/app/add">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">应用名称</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="应用名称" id="appname" class="form-control" name="appname" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">标题</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="标题" id="title" class="form-control" name="title" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">APP分类</label>
                                    <div class="col-md-10">
                                        <select class="form-control input-sm" name="appcategoryid">
                                            <?php foreach($appcategory_list as $l){?>
                                                <option value="<?php echo $l['id']?>"><?php echo $l["category"];?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">混合分类</label>
                                    <div class="col-md-10">
                                        <select class="form-control input-sm" name="categoryid">
                                            <?php foreach($category_list as $l){?>
                                                <option value="<?php echo $l["id"]?>"><?php echo $l["category"];?></option>
                                            <?php }?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">系统</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="系统" id="system" class="form-control" name="system" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="description">版本</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="版本" id="version" class="form-control" name="version" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">大小</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="大小" id="size" class="form-control" name="size" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">PC下载链接</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="PC下载链接" id="pcdownlink" class="form-control" name="pcdownlink" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">安卓下载链接</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="安卓下载链接" id="azdownlink" class="form-control" name="azdownlink" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">苹果下载链接</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="苹果下载链接" id="pgdownlink" class="form-control" name="pgdownlink" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">缩率图</label>
                                    <div class="col-md-10">
                                        <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>
                                        <input type="file" name="thumb" accept="image/*"/>
                                    </div>
                                </div>
                                <div class="from-group">
                                    <label class="col-md-2 control-label">内容介绍</label>
                                    <div class="col-md-10">
                                        <!-- 加载编辑器的容器 -->
                                        <textarea id="container" name="content" style="height:400px;"></textarea>
                                        <!-- 配置文件 -->
                                        <script type="text/javascript" src="/js/bdue/ueditor.config.js"></script>
                                        <!-- 编辑器源码文件 -->
                                        <script type="text/javascript" src="/js/bdue/ueditor.all.js"></script>
                                        <!-- 实例化编辑器 -->
                                        <script type="text/javascript">
                                            var ue = UE.getEditor('container');
                                        </script>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">推荐值</label>
                                    <div class="col-md-10">
                                        <input type="text" required="" placeholder="推荐值" id="recommend" class="form-control" name="recommend" value="0">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">状态</label>
                                    <div class="col-md-10">
                                        <input type="radio" name="status" value="1" checked>已发布
                                        <input type="radio" name="status" value="0">未发布
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button class="btn btn-info" type="submit">添加</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div><!-- panel body -->
            </div>
        </div><!-- content -->
    </div>
</div>
</body>
</html>