<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- site css -->
    <link rel="stylesheet" href="/css/a.min.css">
    <link href="/css/font-face.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/js/site.min.js"></script>
</head>
<body>
<?php include APPLICATION_PATH."/application/modules/Admin/views/site/nav.phtml" ?>
<div class="container-fluid">
    <!--documents-->
    <div class="row row-offcanvas row-offcanvas-left">
        <?php include APPLICATION_PATH."/application/modules/Admin/views/site/header.phtml" ?>
        <div class="col-xs-12 col-sm-9 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $title;?></h3>
                </div>
                <div class="panel-body">
                    <div class="content-row clearfix">
                        <div class="col-md-3">
                            <a href="/admin/category/add" class="btn btn-primary btn-block">添加</a>
                        </div>
                    </div>
                    <div class="content-row">
                        <h2 class="content-row-title"><?php echo $title;?></h2>
                        <div class="row">
                            <table class="table table-hover">
                                <tr>
                                    <th>序号</th>
                                    <th>分类名称</th>
                                    <th>标题</th>
                                    <th>关键字</th>
                                    <th>排序</th>
                                    <th>编辑</th>
                                </tr>
                                <tr>
                                    <?php $i=1; foreach($list as $l){?>
                                        <tr>
                                            <td><?php echo $i;?></td>
                                            <td><?php echo $l['category'];?></td>
                                            <td><?php echo $l['title']?></td>
                                            <td><?php echo $l['keyword']?></td>
                                            <td><?php echo $l['indexorder'];?></td>
                                            <td>
                                                <div class="col-md-6"><a href="/admin/category/edit/id/<?php echo $l['id'];?>" class="btn btn-primary btn-block glyphicon glyphicon-pencil">编辑</a></div>
                                                <div class="col-md-6"><a href="/admin/category/del/id/<?php echo $l['id'];?>" class="btn btn-danger btn-block glyphicon glyphicon-remove">删除</a></div>
                                            </td>
                                        </tr>
                                    <?php $i++;} ?>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div><!-- panel body -->
            </div>
        </div><!-- content -->
    </div>
</div>
</body>
</html>